# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-27 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20161027_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
